package kit;

import org.junit.Test;

import com.di.kit.XmlBuilder;
import com.di.kit.Xml;

/**
 * @author di
 */
public class A {
	@Test
	public void test() {
		String s = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
				+ "<!DOCTYPE mapper PUBLIC \"-//mybatis.org//DTD Mapper 3.0//EN\" \"http://mybatis.org/dtd/mybatis-3-mapper.dtd\">\n"
				+ "<mapper namespace=\"com.d.mapper.MarketingActivityMapper\">\n"
				+ "    <update id=\"updateCloseStoreActivity\">\n" + "        UPDATE `t_marketing_activity` SET\n"
				+ "        `activity_status` = #{activityStatus},`activity_close_time` = now(),`audit_reason`=#{auditReason}\n"
				+ "        WHERE marketing_activity_id = #{activityId}\n" + "    </update>\n" + "\n"
				+ "    <select id=\"listPlatformForActivity\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0\n"
				+ "        <if test=\"planId!=null and planId!=''\">\n"
				+ "            AND `marketing_plan_id`=#{planId}\n" + "        </if>\n"
				+ "        <if test=\"activityName!=null and activityName!=''\">\n"
				+ "            AND `activity_name` like CONCAT(#{activityName},'%')\n" + "        </if>\n"
				+ "        <if test=\"activityId!=null and activityId!=''\">\n"
				+ "            AND `marketing_activity_id`=#{activityId}\n" + "        </if>\n"
				+ "        <if test=\"marketingStatus!=null\">\n" + "            <if test=\"marketingStatus==0\">\n"
				+ "                <![CDATA[ AND `activity_begin_time` > now() ]]>\n" + "            </if>\n"
				+ "            <if test=\"marketingStatus==1\">\n"
				+ "                <![CDATA[ AND `activity_begin_time` < now() AND `activity_end_time` > now() ]]>\n"
				+ "            </if>\n" + "            <if test=\"marketingStatus==2\">\n"
				+ "                <![CDATA[ AND `activity_end_time` < now() ]]>\n" + "            </if>\n"
				+ "        </if>\n" + "        ORDER BY created_at DESC\n" + "    </select>\n" + "\n"
				+ "    <select id=\"listStoreActivity\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0\n"
				+ "        <if test=\"cityId!=null and cityId!=''\">\n" + "            AND `city_id`=#{cityId}\n"
				+ "        </if>\n"
				+ "        <if test=\"activityCreateStartTime!=null and activityCreateStartTime!=''\">\n"
				+ "            <![CDATA[ AND `activity_begin_time`>#{activityCreateStartTime} ]]>\n" + "        </if>\n"
				+ "        <if test=\"activityCreateEndTime!=null and activityCreateEndTime!=''\">\n"
				+ "            <![CDATA[  AND `activity_end_time`<=#{activityCreateEndTime}  ]]>\n" + "        </if>\n"
				+ "        <if test=\"activityStatus!=null and activityStatus!=''\">\n"
				+ "            AND `activity_status`=#{activityStatus}\n" + "        </if>\n"
				+ "        <if test=\"industryParentId!=null and industryParentId!=''\">\n"
				+ "            AND `industry_parent_id`=#{industryParentId}\n" + "        </if>\n"
				+ "        <if test=\"industryId!=null and industryId!=''\">\n"
				+ "            AND `industry_id`=#{industryId}\n" + "        </if>\n"
				+ "        <if test=\"marketingStatus!=null and marketingStatus!=''\">\n"
				+ "            AND `marketing_plan_id` IN (SELECT marketing_plan_id FROM t_marketing_plan WHERE\n"
				+ "            plan_status=#{marketingStatus})\n" + "        </if>\n"
				+ "        <if test=\"storeId!=null and storeId!=''\">\n" + "            AND `store_id`=#{storeId}\n"
				+ "        </if>\n" + "        ORDER BY `created_at` DESC\n" + "    </select>\n" + "\n"
				+ "    <select id=\"listActivityByStoreId\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity`\n" + "        <where>\n"
				+ "          `store_id` = #{storeId} AND `del_flag`=0\n" + "            <if test=\"activityId > 0\">\n"
				+ "              AND `marketing_activity_id` = #{activityId}\n" + "          </if>\n"
				+ "          <if test=\"activityName != ''\">\n"
				+ "              AND `activity_name` LIKE CONCAT(#{activityName},'%')\n" + "          </if>\n"
				+ "          <if test=\"activityStatus == 1\">\n"
				+ "              <![CDATA[ AND `activity_status` = 0 AND `activity_begin_time` < now() AND `activity_end_time` > now() ]]>\n"
				+ "          </if>\n" + "          <if test=\"activityStatus == 2\">\n"
				+ "              <![CDATA[ AND `activity_status` = 0 AND `activity_end_time` < now() ]]>\n"
				+ "          </if>\n" + "          <if test=\"activityStatus == 3\">\n"
				+ "              <![CDATA[ AND `activity_status` = 0 AND `activity_begin_time` > now() ]]>\n"
				+ "          </if>\n" + "          <if test=\"activityStatus == 4\">\n"
				+ "              <![CDATA[ AND `activity_status` = 1 ]]>\n" + "          </if>\n"
				+ "          <if test=\"toolsId!=null and toolsId > 0\">\n"
				+ "              <![CDATA[ AND `marketing_tools_id` = #{toolsId} ]]>\n" + "          </if>\n"
				+ "        </where>\n" + "        <if test=\"sortType == 0\" >\n"
				+ "          ORDER BY `created_at` DESC\n" + "        </if>\n"
				+ "        <if test=\"sortType == 1\" >\n" + "          ORDER BY `created_at`\n" + "        </if>\n"
				+ "    </select>\n" + "\n"
				+ "    <select id=\"getByStoreId\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        <![CDATA[\n"
				+ "            SELECT * FROM `t_marketing_activity` where `store_id` = #{storeId} AND `del_flag`=0 AND `marketing_activity_id` = #{activityId} LIMIT 1\n"
				+ "        ]]>\n" + "    </select>\n" + "    <update id=\"updateSelective\">\n"
				+ "        update t_marketing_activity\n" + "        <set>\n"
				+ "            <if test=\"marketingPlanId != null\">marketing_plan_id=#{marketingPlanId},</if>\n"
				+ "            <if test=\"storeId != null\">store_id=#{storeId},</if>\n"
				+ "            <if test=\"activityName != null\">activity_name=#{activityName},</if>\n"
				+ "            <if test=\"industryParentId != null\">industry_parent_id=#{industryParentId},</if>\n"
				+ "            <if test=\"industryId != null\">industry_id=#{industryId},</if>\n"
				+ "            <if test=\"activityBeginTime != null\">activity_begin_time=#{activityBeginTime},</if>\n"
				+ "            <if test=\"activityEndTime != null\">activity_end_time=#{activityEndTime},</if>\n"
				+ "            <if test=\"activityTerminal != null\">activity_terminal=#{activityTerminal},</if>\n"
				+ "            <if test=\"activityDesc != null\">activity_desc=#{activityDesc},</if>\n"
				+ "            <if test=\"activityRule != null\">activity_rule=#{activityRule},</if>\n"
				+ "            <if test=\"activityRequiredRule != null\">activity_required_rule=#{activityRequiredRule},</if>\n"
				+ "            <if test=\"activityUrl != null\">activity_url=#{activityUrl},</if>\n"
				+ "            <if test=\"marketingToolsId != null\">marketing_tools_id=#{marketingToolsId},</if>\n"
				+ "            <if test=\"activityType != null\">activity_type=#{activityType},</if>\n"
				+ "            <if test=\"activityStatus != null\">activity_status=#{activityStatus},</if>\n"
				+ "            <if test=\"activityCloseTime != null\">activity_close_time=#{activityCloseTime},</if>\n"
				+ "        </set>\n" + "        where marketing_activity_id=#{marketingActivityId}\n"
				+ "    </update>\n"
				+ "    <select id=\"listPlatformAuditActivity\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0 AND `activity_type`=1\n"
				+ "        <if test=\"dateType!=null\">\n" + "            <if test=\"dateType==0\">\n"
				+ "                AND <![CDATA[ TO_DAYS(NOW()) <= (TO_DAYS(`created_at`) + 3)  ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==1\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 7 DAY) <= date(`created_at`) ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==2\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 10 DAY) <= date(`created_at`)  ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==3\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 1 MONTH) <= date(`created_at`) ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==4\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 1 MONTH) > date(`created_at`)  ]]>\n"
				+ "            </if>\n" + "        </if>\n" + "        <if test=\"status!=null\">\n"
				+ "            <if test=\"status==0\">\n"
				+ "                AND <![CDATA[ `activity_begin_time`>now()  ]]>\n" + "            </if>\n"
				+ "            <if test=\"status==1\">\n"
				+ "                AND <![CDATA[ `activity_begin_time`<now() AND `activity_end_time`>now() ]]>\n"
				+ "            </if>\n" + "            <if test=\"status==2\">\n"
				+ "                AND <![CDATA[ `activity_end_time`<now()  ]]>\n" + "            </if>\n"
				+ "        </if>\n" + "        <if test=\"toolsId!=null and toolsId > 0\">\n"
				+ "            <![CDATA[ AND `marketing_tools_id` = #{toolsId} ]]>\n" + "        </if>\n"
				+ "        <if test=\"activityId!=null and activityId!=''\">\n"
				+ "            AND `marketing_activity_id`=#{activityId}\n" + "        </if>\n"
				+ "        <if test=\"activityName!=null and activityName!=''\">\n"
				+ "            AND `activity_name` LIKE CONCAT('%',#{activityName},'%')\n" + "        </if>\n"
				+ "        ORDER BY `created_at` DESC\n" + "    </select>\n"
				+ "    <select id=\"listStoreAuditActivity\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0 AND `activity_type`=2\n"
				+ "        <if test=\"cityId!=null\">\n" + "            AND city_id=#{cityId}\n" + "        </if>\n"
				+ "        <if test=\"dateType!=null\">\n" + "            <if test=\"dateType==0\">\n"
				+ "                AND <![CDATA[ TO_DAYS(NOW()) <= (TO_DAYS(`created_at`) + 3)  ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==1\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 7 DAY) <= date(`created_at`) ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==2\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 10 DAY) <= date(`created_at`)  ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==3\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 1 MONTH) <= date(`created_at`) ]]>\n"
				+ "            </if>\n" + "            <if test=\"dateType==4\">\n"
				+ "                AND <![CDATA[ DATE_SUB(CURDATE(), INTERVAL 1 MONTH) > date(`created_at`)  ]]>\n"
				+ "            </if>\n" + "        </if>\n" + "        <if test=\"auditStatus!=null\">\n"
				+ "            AND `activity_status`=#{auditStatus}\n" + "        </if>\n"
				+ "        <if test=\"toolsId!=null and toolsId > 0\">\n"
				+ "            <![CDATA[ AND `marketing_tools_id` = #{toolsId} ]]>\n" + "        </if>\n"
				+ "        <if test=\"industryParentId!=null and industryParentId!=''\">\n"
				+ "            AND `industry_parent_id`=#{industryParentId}\n" + "        </if>\n"
				+ "        <if test=\"industryId!=null and industryId!=''\">\n"
				+ "            AND `industry_id`=#{industryId}\n" + "        </if>\n"
				+ "        <if test=\"status!=null\">\n" + "            <if test=\"status==1\">\n"
				+ "                AND <![CDATA[ `activity_begin_time`>now()  ]]> AND `activity_status`=0\n"
				+ "            </if>\n" + "            <if test=\"status==2\">\n"
				+ "                AND <![CDATA[ `activity_begin_time`<now() AND `activity_end_time`>now() ]]> AND `activity_status`=0\n"
				+ "            </if>\n" + "            <if test=\"status==3\">\n"
				+ "                AND <![CDATA[ `activity_end_time`<now()  ]]> AND `activity_status`=0\n"
				+ "            </if>\n" + "            <if test=\"status==4\">\n"
				+ "                AND `activity_status`=1\n" + "            </if>\n" + "        </if>\n"
				+ "        <if test=\"storeIds!=null\">\n" + "            AND `store_id` IN\n"
				+ "            <foreach item=\"storeId\" index=\"index\" collection=\"storeIds\" open=\"(\" separator=\",\" close=\")\">\n"
				+ "                #{storeId}\n" + "            </foreach>\n" + "        </if>\n"
				+ "        ORDER BY created_at DESC\n" + "    </select>\n"
				+ "    <select id=\"listByActivityBeginTime\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0\n"
				+ "        <if test=\"begin!=null\">\n"
				+ "            <![CDATA[ AND `activity_begin_time`>#{begin} ]]>\n" + "        </if>\n"
				+ "        <if test=\"end!=null\">\n"
				+ "            <![CDATA[  AND `activity_begin_time`<=#{end}  ]]>\n" + "        </if>\n"
				+ "        ORDER BY `created_at` DESC\n" + "    </select>\n"
				+ "    <select id=\"listByActivityEndTime\" resultType=\"com.jiehun.marketing.entity.MarketingActivity\">\n"
				+ "        SELECT * FROM `t_marketing_activity` WHERE `del_flag`=0\n"
				+ "        <if test=\"begin!=null\">\n" + "            <![CDATA[ AND `activity_end_time`>#{begin} ]]>\n"
				+ "        </if>\n" + "        <if test=\"end!=null\">\n"
				+ "            <![CDATA[  AND `activity_end_time`<=#{end}  ]]>\n" + "        </if>\n"
				+ "        ORDER BY `created_at` DESC\n" + "    </select>\n" + "</mapper>";
		Xml.toMap(s);
		XmlBuilder parse = new XmlBuilder().parse(s);
		parse.rootNode().toFormatString();
		System.out.println(s);
	}
}
